# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go run main.go"
  bin = "tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor"]
  exclude_regex = ["_test\\.go"]
  delay = 1000 # миллисекунды

[log]
  time = true
  color = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
  error = "red"
